name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go modules
        shell: bash
        if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        run: go mod download
      - name: Go build
        shell: bash
        run: go build ./...
      - name: Go test
        shell: bash
        run: go test ./...
